apiVersion: v1
kind: Pod
metadata:
  name: wordpress1-pod
  namespace: wordpress1
  labels:
    app: wordpress1-pod
spec:
  containers:
  - name: wordpress1
    image: wordpress:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress1-service
  namespace: wordpress1
spec:
  selector:
    app: wordpress1-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
