apiVersion: v1
kind: Pod
metadata:
  name: wordpress3-pod
  namespace: wordpress3
  labels:
    app: wordpress3-pod
spec:
  containers:
  - name: wordpress3
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress3-mysql-service
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress3-service
  namespace: wordpress3
spec:
  selector:
    app: wordpress3-pod
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80
