apiVersion: v1
kind: Pod
metadata:
  name: wordpress1-pod
  namespace: wordpress1
  labels:
    app: wordpress1-pod
spec:
  containers:
  - name: wordpress1
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress1-mysql-service
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress1-service
  namespace: wordpress1
spec:
  selector:
    app: wordpress1-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ingress
  namespace: wordpress1
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/wordpress1"
        backend:
          service:
            name: wordpress1-service
            port:
              number: 3000
