apiVersion: v1
kind: Pod
metadata:
  name: wordpress1-pod
  labels:
    app: wordpress1-pod
spec:
  containers:
  - name: wordpress1
    image: wordpress:latest
    command: ["/bin/sh", "-c", "ln -s /var/www/html /var/www/html/wordpress1"]
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress1-mysql-service:3310
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress1-service
spec:
  selector:
    app: wordpress1-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
