apiVersion: v1
kind: ConfigMap
metadata: 
  name: wordpress1-configmap
data:
  uploads.ini: |
    file_uploads = On
    memory_limit = 8G
    upload_max_filesize = 8G
    post_max_size = 8G
    max_execution_time = 600
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress1-pod
  labels:
    app: wordpress1-pod
spec:
  containers:
  - name: wordpress1
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress1-mysql-service:3310
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_CONFIG_EXTRA
      value: |
        define('WP_SITEURL', 'http://172.104.100.43/wordpress1/');
        define('WP_HOME', 'http://172.104.100.43/wordpress1/');
        define('WP_CONTENT_URL', 'http://172.104.100.43/wordpress1/wp-content/');
    volumeMounts:
    - name: uploads
      mountPath: /usr/local/etc/php/conf.d/uploads.ini
  volumes:
    - name: uploads
      configMap:
        name: wordpress1-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress1-service
spec:
  selector:
    app: wordpress1-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
