apiVersion: v1
kind: Pod
metadata:
  name: wordpress3-pod
  labels:
    app: wordpress3-pod
spec:
  containers:
  - name: wordpress3
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress3-mysql-service:3312
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_CONFIG_EXTRA
      value: |
        define('WP_SITEURL', 'http://172.104.100.43/wordpress3/');
        define('WP_HOME', 'http://172.104.100.43/wordpress3/');
        define('WP_CONTENT_URL', 'http://172.104.100.43/wordpress3/wp-content/');
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress3-service
spec:
  selector:
    app: wordpress3-pod
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80
