apiVersion: v1
kind: ConfigMap
metadata: 
  name: wordpress3-configmap
data:
  uploads.ini: |
    file_uploads = On
    memory_limit = 8G
    upload_max_filesize = 8G
    post_max_size = 8G
    max_execution_time = 600
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress4-pod
  labels:
    app: wordpress4-pod
spec:
  containers:
  - name: wordpress4
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress4-mysql-service:3313
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_CONFIG_EXTRA
      value: |
        define('WP_SITEURL', 'http://172.104.100.43/wordpress4/');
        define('WP_HOME', 'http://172.104.100.43/wordpress4/');
        define('WP_CONTENT_URL', 'http://172.104.100.43/wordpress4/wp-content/');
    volumeMounts:
      - name: uploads
        mountPath: /usr/local/etc/php/conf.d/
  volumes:
    - name: uploads
      configMap:
        name: wordpress4-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress4-service
spec:
  selector:
    app: wordpress4-pod
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 80
