apiVersion: v1
kind: Pod
metadata:
  name: wordpress2-pod
  namespace: wordpress2
  labels:
    app: wordpress2-pod
spec:
  containers:
  - name: wordpress2
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress2-mysql-service
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_NAME
      value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress2-service
  namespace: wordpress2
spec:
  selector:
    app: wordpress2-pod
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 80
