apiVersion: v1
kind: Pod
metadata:
  name: wordpress2-pod
  namespace: wordpress2
  labels:
    app: wordpress2-pod
spec:
  containers:
  - name: wordpress2
    image: wordpress:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress2-service
  namespace: wordpress2
spec:
  selector:
    app: wordpress2-pod
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 80
