apiVersion: v1
kind: Pod
metadata:
  name: wordpress1-mysql-pod
  labels:
    app: wordpress1-mysql-pod
spec:
  containers:
  - name: wordpress1-mysql
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-mysql-secret
          key: wordpress-mysql-password
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-mysql-secret
          key: wordpress-mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress1-mysql-service
spec:
  selector:
    app: wordpress1-mysql-pod
  ports:
    - protocol: TCP
      port: 3310
      targetPort: 3306
