apiVersion: v1
kind: Pod
metadata:
  name: wordpress3-mysql-pod
  namespace: wordpress3
  labels:
    app: wordpress3-mysql-pod
spec:
  containers:
  - name: wordpress3-mysql
    image: mysql:5.7
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress3-mysql-service
  namespace: wordpress3
spec:
  selector:
    app: wordpress3-mysql-pod
  ports:
    - protocol: TCP
      port: 3312
      targetPort: 3306
