apiVersion: v1
kind: Pod
metadata:
  name: wordpress1-mysql-pod
  labels:
    app: wordpress1-mysql-pod
spec:
  containers:
  - name: wordpress1-mysql
    image: mysql:5.7
    args:
    - --default_authentication_plugin=mysql_native_password
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD
      value: root
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress1-mysql-service
spec:
  selector:
    app: wordpress1-mysql-pod
  ports:
    - protocol: TCP
      port: 3310
      targetPort: 3306
